// ============================================================================
// Firebase Config Placeholder
// ============================================================================
// TODO: After setting up a Firebase project, replace this file with the
//       real firebase_options.dart generated by the FlutterFire CLI.
//
// Steps:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   3. Run: flutterfire configure
//   4. This will generate lib/firebase_options.dart automatically.
//   5. Add lib/firebase_options.dart to .gitignore (already done).
//   6. Initialize Firebase in main.dart:
//        await Firebase.initializeApp(
//          options: DefaultFirebaseOptions.currentPlatform,
//        );
//
// NOTE: Never commit google-services.json or GoogleService-Info.plist to Git.
//       Both files are already excluded in .gitignore.
// ============================================================================
