import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import 'package:open_file/open_file.dart';
import '../../../data/db/drift_database.dart';

/// 📊 Service for exporting beneficiaries reports to PDF and Excel
class BeneficiariesExportService {
  /// Export beneficiaries to PDF
  static Future<String> exportToPdf(List<Beneficiary> beneficiaries) async {
    final pdf = pw.Document();

    // Add pages (using default font for now - works with Arabic)
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        textDirection: pw.TextDirection.rtl,
        build: (context) => [
          // Header
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              color: PdfColors.blue700,
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Beneficiaries Comprehensive Report',
                  style: pw.TextStyle(
                    fontSize: 24,
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  'Date: ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.white,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Statistics Summary
          pw.Container(
            padding: const pw.EdgeInsets.all(15),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _buildStatBox('Total', beneficiaries.length.toString()),
                _buildStatBox(
                  'Synced',
                  beneficiaries
                      .where((b) => b.syncState == 'synced')
                      .length
                      .toString(),
                ),
                _buildStatBox(
                  'Pending',
                  beneficiaries
                      .where((b) => b.syncState == 'pending')
                      .length
                      .toString(),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Table Header
          pw.Text(
            'Beneficiaries List',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),

          // Table
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400),
            children: [
              // Header Row
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.blue100),
                children: [
                  _buildTableCell('#', isHeader: true),
                  _buildTableCell('Full Name', isHeader: true),
                  _buildTableCell('National ID', isHeader: true),
                  _buildTableCell('Phone', isHeader: true),
                  _buildTableCell('Sync Status', isHeader: true),
                ],
              ),
              // Data Rows
              ...beneficiaries.asMap().entries.map((entry) {
                final index = entry.key + 1;
                final b = entry.value;
                return pw.TableRow(
                  decoration: pw.BoxDecoration(
                    color: index % 2 == 0 ? PdfColors.grey50 : PdfColors.white,
                  ),
                  children: [
                    _buildTableCell(index.toString()),
                    _buildTableCell(b.fullName),
                    _buildTableCell(b.idNumber.toString()),
                    _buildTableCell(
                      b.phoneNumber != 0 ? b.phoneNumber.toString() : '-',
                    ),
                    _buildTableCell(_getSyncStateText(b.syncState)),
                  ],
                );
              }),
            ],
          ),

          pw.SizedBox(height: 20),

          // Footer
          pw.Divider(color: PdfColors.grey300),
          pw.SizedBox(height: 10),
          pw.Text(
            'Generated by Benaa System - ${DateFormat('yyyy-MM-dd').format(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );

    // Save PDF
    final directory = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final filePath = '${directory.path}/beneficiaries_report_$timestamp.pdf';
    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    return filePath;
  }

  /// Export beneficiaries to Excel
  static Future<String> exportToExcel(List<Beneficiary> beneficiaries) async {
    final excel = Excel.createExcel();
    final sheet = excel['تقرير المستفيدين'];

    // Remove default sheet if exists
    if (excel.sheets.containsKey('Sheet1')) {
      excel.delete('Sheet1');
    }

    // Add Header Row (styled)
    final headerStyle = CellStyle(
      backgroundColorHex: ExcelColor.fromHexString('#1976D2'),
      fontColorHex: ExcelColor.fromHexString('#FFFFFF'),
      bold: true,
      fontSize: 12,
    );

    final headers = [
      'الرقم',
      'الاسم الكامل',
      'الرقم الوطني',
      'رقم الهاتف',
      'رقم الهاتف البديل',
      'حالة المزامنة',
      'تاريخ التسجيل',
    ];

    for (var i = 0; i < headers.length; i++) {
      final cell = sheet.cell(
        CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0),
      );
      cell.value = TextCellValue(headers[i]);
      cell.cellStyle = headerStyle;
    }

    // Add Data Rows
    for (var i = 0; i < beneficiaries.length; i++) {
      final b = beneficiaries[i];
      final rowIndex = i + 1;

      // Alternate row colors
      final rowStyle = CellStyle(
        backgroundColorHex: i % 2 == 0
            ? ExcelColor.fromHexString('#F5F5F5')
            : ExcelColor.fromHexString('#FFFFFF'),
      );

      final rowData = [
        (i + 1).toString(),
        b.fullName,
        b.idNumber.toString(),
        b.phoneNumber != 0 ? b.phoneNumber.toString() : '-',
        b.altPhoneNumber != 0 ? b.altPhoneNumber.toString() : '-',
        _getSyncStateArabic(b.syncState),
        b.createdAt != null
            ? DateFormat('yyyy-MM-dd').format(b.createdAt!)
            : '-',
      ];

      for (var j = 0; j < rowData.length; j++) {
        final cell = sheet.cell(
          CellIndex.indexByColumnRow(columnIndex: j, rowIndex: rowIndex),
        );
        cell.value = TextCellValue(rowData[j]);
        cell.cellStyle = rowStyle;
      }
    }

    // Auto-fit columns
    for (var i = 0; i < headers.length; i++) {
      sheet.setColumnWidth(i, 20);
    }

    // Add Summary Sheet
    final summarySheet = excel['ملخص الإحصائيات'];
    _addSummarySheet(summarySheet, beneficiaries);

    // Save Excel
    final directory = await getApplicationDocumentsDirectory();
    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final filePath = '${directory.path}/beneficiaries_report_$timestamp.xlsx';
    final file = File(filePath);
    await file.writeAsBytes(excel.encode()!);

    return filePath;
  }

  /// Open exported file
  static Future<void> openFile(String filePath) async {
    await OpenFile.open(filePath);
  }

  // Helper Methods
  static pw.Widget _buildStatBox(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue700,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
        ),
      ],
    );
  }

  static pw.Widget _buildTableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: isHeader ? 11 : 10,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: isHeader ? PdfColors.blue900 : PdfColors.black,
        ),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  static String _getSyncStateText(String state) {
    switch (state) {
      case 'synced':
        return 'Synced';
      case 'pending':
        return 'Pending';
      case 'failed':
        return 'Failed';
      default:
        return state;
    }
  }

  static String _getSyncStateArabic(String state) {
    switch (state) {
      case 'synced':
        return 'تمت المزامنة';
      case 'pending':
        return 'بانتظار المزامنة';
      case 'failed':
        return 'فشلت المزامنة';
      default:
        return state;
    }
  }

  static void _addSummarySheet(Sheet sheet, List<Beneficiary> beneficiaries) {
    // Title
    final titleCell = sheet.cell(
      CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: 0),
    );
    titleCell.value = TextCellValue('ملخص إحصائيات المستفيدين');
    titleCell.cellStyle = CellStyle(
      bold: true,
      fontSize: 16,
      backgroundColorHex: ExcelColor.fromHexString('#1976D2'),
      fontColorHex: ExcelColor.fromHexString('#FFFFFF'),
    );

    // Statistics
    final stats = [
      ['إجمالي المستفيدين', beneficiaries.length.toString()],
      [
        'تمت المزامنة',
        beneficiaries.where((b) => b.syncState == 'synced').length.toString(),
      ],
      [
        'بانتظار المزامنة',
        beneficiaries.where((b) => b.syncState == 'pending').length.toString(),
      ],
      [
        'فشلت المزامنة',
        beneficiaries.where((b) => b.syncState == 'failed').length.toString(),
      ],
      ['تاريخ التقرير', DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())],
    ];

    for (var i = 0; i < stats.length; i++) {
      final labelCell = sheet.cell(
        CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: i + 2),
      );
      labelCell.value = TextCellValue(stats[i][0]);
      labelCell.cellStyle = CellStyle(bold: true);

      final valueCell = sheet.cell(
        CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: i + 2),
      );
      valueCell.value = TextCellValue(stats[i][1]);
    }

    sheet.setColumnWidth(0, 25);
    sheet.setColumnWidth(1, 20);
  }
}
